### PR TITLE
generate.py: create emulation ABC

### PR DESCRIPTION
**Pull request by sajal50**
This commit is in precursor to adding emulation layer for windows.
This cleans up creating an emaulation settings instance which can be reused.

### CODE REVIEW

**Comment by frutiger** [comment]
I was thinking of something closer to ~https://github.com/frutiger/ncg/commit/1d19cbb4b9bfc05c5391200e28a41641f951d06f~ https://github.com/frutiger/ncg/commit/0c84af5451db0733c0374ba8978bd8530e19b994.

Reasoning:
1. avoid the fancy ABC formalism and be a bit more duck-typed just to be slightly more _Pythonic_
1. fold all the `target.get(..., [])` style operations into this new `Properties` class (open for a better name, but couldn't think of anything better yet)
1. remove some of nested functions which are harder to understand, and move all the otherwise closed over variables into member variables
1. provide a natural extension point for other properties we may be [pulling out of the configured target incorrectly](https://github.com/frutiger/ncg/blob/87c6f6aba7b16183cfe7d298a801b0edd9ce5897/generate.py#L398)

**NOTE**: I have only run `generate.py` on macOS and not tried building the result, so if we do decide to proceed with the suggestion, we should test it on our three platforms.

**Comment by sajal50** [comment]
I am not sure if there is any need to create an instance of emulation class multiple times. And due to that, we would have to feed the args required for it at every place it needs to be used. We really have all the info needed to create the instance upfront and then use the same instance every where it is needed and not have `platform` passed around.

**Comment by sajal50** [comment]
Moreover,
```
    def defines(self, configuration_name, configuration):
        return configuration.get('defines', [])

    def include_dirs(self, configuration_name, configuration):
        return configuration.get('include_dirs', []),
```
these two methods feel weird to have on the class. They don't really use any data member.

**Comment by frutiger** [comment]
> Moreover,
> 
> ```
>     def defines(self, configuration_name, configuration):
>         return configuration.get('defines', [])
> 
>     def include_dirs(self, configuration_name, configuration):
>         return configuration.get('include_dirs', []),
> ```
> 
> these two methods feel weird to have on the class. They don't really use any data member.

This is a fair point, they should probably be tagged `@classmethod`. I still want to keep the same interface so from the caller's side it is abstracted.

**Comment by frutiger** [comment]
> I am not sure if there is any need to create an instance of emulation class multiple times. And due to that, we would have to feed the args required for it at every place it needs to be used. We really have all the info needed to create the instance upfront and then use the same instance every where it is needed and not have `platform` passed around.

Unless I missed something (and I probably have) I only see us creating these `Properties` objects the same number of times we were calling `get_flags_factory(...)`.

**Comment by sajal50** [comment]
> Unless I missed something (and I probably have) I only see us creating these Properties objects the same number of times we were calling get_flags_factory(...).

That is true. But we don't really _have_ to. For example, in my sample impl in this PR, we create it only once.

**Comment by frutiger** [comment]
It's true that by conflating platform+target and category, we are computing the settings multiple times. In practice, this will once per category, and we only have two categories, so it's probably not a huge deal. I was really trying to avoid [this kind of pattern](https://github.com/frutiger/ncg/pull/4/files#diff-801d46835a8aee4eba56246cd21be7ae8628884a17b2648ec6afc8786e319af8L51-L53) (which I know I am originally to blame for 😄).

**Comment by sajal50** [comment]
I think you are right. In fairness, this code is for readability than for performance. What you have LGTM. I'll go through it again and see if we can have some middle ground, otherwise I'll update this PR with the changes.

**Comment by frutiger** [comment]
Fixed in #5.

**Pull request closed without merging**
